name: Syzkaller Integration

on:
  workflow_dispatch:

jobs:
  syzk:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/799795028847/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github@sdcpocs.iam.gserviceaccount.com'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install google-auth requests
      - name: Update syzkaller pipeline
        run: |
          cd fuzzer/syzkaller
          ./process_osv.sh output.json > output-new.json && (cat output-new.json | tee output.json)
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output.json
          git commit -m '[automatic] update output.json' || true
          git push
