name: Test Syzkaller Integration

on:
  workflow_dispatch:

jobs:
  syzk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test sqlite
        run: |
          wget -q https://linux-mirror-db.storage.googleapis.com/mirror.sl3
          sqlite3 -json mirror.sl3 'SELECT `syzkaller_ref`, `fixed_by`, IIF(LENGTH(introduced_by_short)<4, null, (SELECT `commit` FROM tags WHERE `commit`>=`introduced_by_short` AND `commit`<`introduced_by_short`||"g")) `introduced_by` FROM (SELECT `syzkaller_ref`, `fixed_by`, (SELECT SUBSTR(`fixes`, 0, INSTR(`fixes`, " ")) FROM `fixes` WHERE `commit`=`fixed_by`) `introduced_by_short` FROM (SELECT `reported_by` `syzkaller_ref`, `commit` `fixed_by` FROM `reported_by` UNION ALL SELECT "FOOBAR" `syzkaller_ref`, `commit` `fixed_by` FROM syzkaller))'
